// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbepoxajjdxhkwotfelh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZXBveGFqamR4aGt3b3RmZWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzAyNzksImV4cCI6MjA3MjE0NjI3OX0.KWZk6UZzGE6O7xetlOV6Jlx004ko7y0BMeZOOvI9Ha4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});